### PR TITLE
Avoid template strings to support node 0.10 as a build platform

### PR DESCRIPTION
**Pull request by phated**
I think this is a pretty simple change and lets this transform run in node 0.10+

Ran into this when trying to optimize some code on node 0.10.x

### CODE REVIEW

**Comment by shama** [comment]
Sorry looks like I forgot about this PR. I think I'd rather just convert the template literals to strings instead if Node 0.10 support is needed.

**Comment by phated** [comment]
Cool.  Should I update this PR or send a new one?

**Comment by shama** [comment]
Oh if you wanted to update this PR that would be awesome. Thanks!

**Comment by phated** [comment]
@shama updated!  I ran the babel transform against the index and test files and copied the relevant lines over (removing the semicolons).  Tests should be passing.  Thanks!

**Comment by shama** [comment]
Cool! Thanks a bunch!

**Pull request merged**
